spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WH2zzZ/config-center.git
          search-paths: /microserver/gateway
          username: WH2zzZ
          password: wh942966