name: Docker Image CI

on: 
  push:
    branches: 
      - master

jobs:
  first-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Set up jdk1.8
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      - name: Build with Maven 
        run: maven package --file pom.xml
  second-docker:
    needs: [first-build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: 
         docker build . -t wanghan/configurationserver:1.0
